echo "Current Netlify context: $CONTEXT"
echo "Current branch: $BRANCH"

[build]
  publish = "dist"
[context.production]
  command = "pnpm build:prod"

[context.development]
  command = "pnpm build:dev"

[context.deploy-preview]
  command = "pnpm build:preview"